[env:black_f407ve]
platform = ststm32
board = black_f407ve
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
lib_extra_dirs = middleware
build_flags = 
    -O3
    -DSTM32F407xx
    -DUSE_HAL_DRIVER
    -DARM_MATH_CM4
    -DPEANUT_GB_HIGH_LCD_ACCURACY=0
build_unflags = -Os